#!/usr/bin/env pwsh
# Flutter setup helper: Windows / macOS / Linux
# Prompts y/n for Android SDK/AVD, Web, Desktop. Flutter is mandatory if missing.
$global:PathsAdded = @()

function Prompt-YesNo($message) {
    $resp = Read-Host "$message [y/N]"
    return $resp -match '^(y|yes)$'
}

function Detect-Platform {
    if ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)) { return "windows" }
    elseif ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::OSX)) { return "macos" }
    else { return "linux" }
}

function Tool-Root {
    $platform = Detect-Platform
    if ($platform -eq "windows") { return (Join-Path $Env:USERPROFILE "develop") }
    return (Join-Path $HOME "develop")
}

function Ensure-Command($cmd) { return (Get-Command $cmd -ErrorAction SilentlyContinue) }
function Ensure-Directory($path) { if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path | Out-Null } }
function Add-ToPath($path) {
    $global:PathsAdded = ($global:PathsAdded + $path) | Select-Object -Unique
    if (-not ($Env:PATH -like "*$path*")) {
        Write-Host "Adding $path to PATH (user scope)..."
        setx PATH "$Env:PATH;$path" > $null
        $Env:PATH = "$path;$Env:PATH"
    } else {
        Write-Host "$path already in PATH."
    }
}
function Download-File($url, $destPath) {
    if (Test-Path $destPath) {
        Write-Host "Found existing archive at $destPath, skipping download."
        return
    }
    Write-Host "Downloading $url ..."
    $destDir  = Split-Path $destPath -Parent
    $destFile = Split-Path $destPath -Leaf
    Ensure-Directory $destDir
    $downloader = $null
    if (Ensure-Command "aria2c") { $downloader = "aria2c" }
    elseif (Ensure-Command "curl.exe") { $downloader = "curl" }
    if ($downloader -eq "aria2c") {
        aria2c -x 8 -s 8 -d $destDir -o $destFile $url
    } elseif ($downloader -eq "curl") {
        curl.exe -L --retry 3 --retry-delay 2 -o $destPath $url
    } else {
        Invoke-WebRequest -Uri $url -OutFile $destPath
    }
}

function Extract-Archive($zipPath, $destPath) {
    Ensure-Directory $destPath
    if (Ensure-Command "tar") {
        Write-Host "Extracting with tar: $zipPath -> $destPath"
        tar -xf "$zipPath" -C "$destPath" | Out-Null
    } else {
        Write-Host "Extracting with Expand-Archive (may be slower): $zipPath -> $destPath"
        Expand-Archive -Path $zipPath -DestinationPath $destPath -Force
    }
}

function Resolve-AndroidTool($sdkRoot, $platform, $toolName) {
    if ($platform -eq "windows") {
        $candidates = @(
            (Join-Path $sdkRoot "cmdline-tools\latest\bin\$toolName.bat"),
            (Join-Path $sdkRoot "cmdline-tools\latest\cmdline-tools\bin\$toolName.bat")
        )
    } else {
        $candidates = @(
            (Join-Path $sdkRoot "cmdline-tools/bin/$toolName"),
            (Join-Path $sdkRoot "cmdline-tools/latest/bin/$toolName"),
            (Join-Path $sdkRoot "cmdline-tools/latest/cmdline-tools/bin/$toolName")
        )
    }
    foreach ($c in $candidates) { if (Test-Path $c) { return $c } }
    return $toolName
}

function Write-EnvScript {
    $envRoot = Tool-Root
    $envFile = Join-Path $envRoot "flutter-env.ps1"
    $lines = @()
    $lines += "# Generated by flutter-setup.ps1"
    $lines += "# Dot-source this file to refresh your current PowerShell session."
    $lines += ""
    $lines += '$ErrorActionPreference = "Stop"'
    if ($Env:ANDROID_SDK_ROOT) { $lines += '$Env:ANDROID_SDK_ROOT = "' + $Env:ANDROID_SDK_ROOT + '"' }
    if ($Env:ANDROID_HOME)     { $lines += '$Env:ANDROID_HOME = "' + $Env:ANDROID_HOME + '"' }
    if ($Env:JAVA_HOME)       { $lines += '$Env:JAVA_HOME = "' + $Env:JAVA_HOME + '"' }
    $paths = ($global:PathsAdded | Where-Object { $_ -ne $null } | Select-Object -Unique)
    if ($paths.Count -gt 0) {
        $pathsLiteral = $paths | ForEach-Object { '"' + $_ + '"' } | Sort-Object -Unique
        $lines += '$__paths = @(' + ($pathsLiteral -join ',') + ')'
        $lines += 'foreach ($p in $__paths) { if (-not ($Env:PATH -like "*$p*")) { $Env:PATH = "$p;$Env:PATH" } }'
    }
    Set-Content -Path $envFile -Value $lines -Encoding ascii
    Write-Host "Environment helper written to $envFile"
    Write-Host "To refresh current shell without reopening, run:"
    Write-Host ". `"$envFile`""
}

function Ensure-Java {
    $script:JavaHomeSet = $null
    if ($Env:JAVA_HOME -and (Test-Path $Env:JAVA_HOME)) {
        Write-Host "JAVA_HOME detected at $Env:JAVA_HOME"
        $script:JavaHomeSet = $Env:JAVA_HOME
        return
    }
    if (Ensure-Command "java") {
        Write-Host "Java found in PATH."
        return
    }
    $platform = Detect-Platform
    if (-not (Prompt-YesNo "Java/JDK not found. Install JDK 17 now?")) { return }
    switch ($platform) {
        "windows" {
            $jdkUrl = "https://aka.ms/download-jdk/microsoft-jdk-17-windows-x64.zip"
            $destRoot = Tool-Root
            $zipPath = Join-Path $destRoot "jdk17-win.zip"
            Download-File $jdkUrl $zipPath
            $jdkDest = Join-Path $destRoot "jdk"
            Ensure-Directory $jdkDest
            Write-Host "Extracting JDK to $jdkDest ..."
            Extract-Archive $zipPath $jdkDest
            $extracted = Get-ChildItem -Directory $jdkDest | Where-Object { $_.Name -like "jdk-17*" } | Select-Object -First 1
            if ($null -eq $extracted) { Write-Host "Could not locate extracted JDK folder."; return }
            $javaHome = $extracted.FullName
            Write-Host "Setting JAVA_HOME=$javaHome"
            $Env:JAVA_HOME = $javaHome
            setx JAVA_HOME "$javaHome" > $null
            Add-ToPath (Join-Path $javaHome "bin")
            $script:JavaHomeSet = $javaHome
        }
        "macos" {
            brew install openjdk@17
            $javaHome = & /usr/libexec/java_home -v 17 2>$null
            if ($javaHome) {
                Write-Host "Setting JAVA_HOME=$javaHome"
                $Env:JAVA_HOME = $javaHome
                echo "export JAVA_HOME=$javaHome" >> ~/.zprofile
                echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> ~/.zprofile
                $script:JavaHomeSet = $javaHome
            }
        }
        default {
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            $javaHome = "/usr/lib/jvm/java-17-openjdk-amd64"
            if (Test-Path $javaHome) { $Env:JAVA_HOME = $javaHome; $script:JavaHomeSet = $javaHome }
        }
    }
}

# Ensure base tool directory exists
Ensure-Directory (Tool-Root)

function Install-Flutter {
    $platform = Detect-Platform
    if (Ensure-Command "flutter") { Write-Host "Flutter already installed."; return }
    Write-Host "Flutter SDK not found. If flutter is already installed, ensure it's in your PATH."
    if (-not (Prompt-YesNo "Would you like to install Flutter?")) { return }
    switch ($platform) {
        "windows" {
            $zipUrl   = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.38.5-stable.zip"
            $destRoot = Tool-Root
            Ensure-Directory $destRoot
            $zipPath  = Join-Path $destRoot "flutter_windows_3.38.5-stable.zip"
            $destRoot = Tool-Root
            $destPath = Join-Path $destRoot "flutter"
            Download-File $zipUrl $zipPath
            Write-Host "Extracting to $destPath ..."
            if (Test-Path $destPath) {
                Write-Host "Directory already exists. Extraction will overwrite existing files."
            }
            Extract-Archive $zipPath $destRoot
            $flutterBin = "$destPath\bin"
            Add-ToPath $flutterBin
            Write-Host "Restart your shell if PATH does not refresh."
        }
        "macos"   { brew install --cask flutter }
        "linux"   {
            sudo apt-get update
            sudo apt-get install -y curl unzip xz-utils
            curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.0-stable.tar.xz
            sudo mkdir -p /opt/flutter
            sudo tar -xf flutter_linux_3.22.0-stable.tar.xz -C /opt
            sudo ln -sf /opt/flutter/bin/flutter /usr/local/bin/flutter
        }
    }
    Write-Host "Restart your shell if PATH does not refresh."
}

function Setup-Android {
    if (-not (Prompt-YesNo "Install Android SDK + platform-tools + build-tools?")) { return }
    $platform = Detect-Platform
    Ensure-Java
    $sdkRoot = switch ($platform) {
        "windows" { Join-Path (Tool-Root) "android-sdk" }
        "macos"   { "$HOME/Library/Android/sdk" }
        default   { "/usr/lib/android-sdk" }
    }
    if ($platform -eq "windows") {
        Ensure-Directory $sdkRoot
        $zipUrl = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"
        $zipPath = Join-Path (Tool-Root) "commandlinetools-win.zip"
        Download-File $zipUrl $zipPath
        $cmdlineBase = Join-Path $sdkRoot "cmdline-tools"
        $cmdlineDest = Join-Path $cmdlineBase "latest"
        $tempExtract = Join-Path $cmdlineBase "_tmp"
        Ensure-Directory $cmdlineBase
        if (Test-Path $cmdlineDest) { Remove-Item -Recurse -Force $cmdlineDest }
        Ensure-Directory $tempExtract
        Write-Host "Extracting command line tools to $tempExtract ..."
        Extract-Archive $zipPath $tempExtract
        # The archive contains a top-level cmdline-tools folder; move its contents to latest
        $extractedFolder = Join-Path $tempExtract "cmdline-tools"
        Ensure-Directory $cmdlineDest
        Get-ChildItem -Path $extractedFolder | ForEach-Object { Move-Item -Path $_.FullName -Destination $cmdlineDest -Force }
        Remove-Item -Recurse -Force $tempExtract
    } elseif ($platform -eq "macos") {
        brew install --cask android-commandlinetools
    } else {
        sudo apt-get update
        sudo apt-get install -y unzip
        cd /tmp
        curl -LO https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
        sudo unzip -o commandlinetools-linux-11076708_latest.zip -d /usr/lib/android-sdk/cmdline-tools
        sudo ln -sf /usr/lib/android-sdk /opt/android-sdk
    }
    Write-Host "Setting ANDROID_SDK_ROOT=$sdkRoot"
    $Env:ANDROID_SDK_ROOT = $sdkRoot
    $Env:ANDROID_HOME = $sdkRoot
    if ($platform -eq "windows") { setx ANDROID_SDK_ROOT "$sdkRoot" > $null }
    if ($platform -eq "windows") { setx ANDROID_HOME "$sdkRoot" > $null }
    $sdkmanager = Resolve-AndroidTool $sdkRoot $platform "sdkmanager"
    & $sdkmanager --sdk_root=$sdkRoot --install `
        "platform-tools" `
        "platforms;android-34" `
        "platforms;android-36" `
        "build-tools;34.0.0" `
        "build-tools;36.0.0" `
        "build-tools;28.0.3"
    if ($platform -eq "windows") { Add-ToPath (Join-Path $sdkRoot "platform-tools") }
    & $sdkmanager --sdk_root=$sdkRoot --licenses
}

function Setup-AVD {
    if (-not (Prompt-YesNo "Create a default Android emulator (AVD)?")) { return }
    $platform = Detect-Platform
    $sdkRoot = $Env:ANDROID_SDK_ROOT
    $sdkmanager = Resolve-AndroidTool $sdkRoot $platform "sdkmanager"
    $avdmanager = Resolve-AndroidTool $sdkRoot $platform "avdmanager"
    & $sdkmanager --sdk_root=$sdkRoot --install "system-images;android-34;google_apis;x86_64"
    & $avdmanager create avd -n pixel_api34 -k "system-images;android-34;google_apis;x86_64" -d pixel_5 --device pixel_5 --sdcard 512M --force
}

function Enable-Web {
    if (Prompt-YesNo "Enable Flutter web support?") { flutter config --enable-web }
}

function Enable-Android {
    if (Prompt-YesNo "Enable Flutter Android support?") { flutter config --enable-android }
}

function Ensure-Frontend-Platforms {
    $repoRoot = Split-Path -Parent $PSScriptRoot
    $frontend = Join-Path $repoRoot "frontend"
    if (-not (Test-Path $frontend)) { return }

    $needsAndroid = -not (Test-Path (Join-Path $frontend "android"))
    $needsWeb = -not (Test-Path (Join-Path $frontend "web"))
    if (-not ($needsAndroid -or $needsWeb)) { return }

    $platforms = @()
    if ($needsAndroid) { $platforms += "android" }
    if ($needsWeb) { $platforms += "web" }
    $platformArg = $platforms -join ","

    Write-Host "Generating missing Flutter platforms in $frontend ($platformArg)..."
    Push-Location $frontend
    flutter create --platforms $platformArg .
    Pop-Location
}

function Enable-Desktop {
    $platform = Detect-Platform
    if ($platform -eq "windows") {
        if (Prompt-YesNo "Enable Windows desktop (requires Visual Studio C++ workload)?") { flutter config --enable-windows-desktop }
    } elseif ($platform -eq "macos") {
        if (Prompt-YesNo "Enable macOS desktop (requires Xcode tools)?") { flutter config --enable-macos-desktop }
    } else {
        if (Prompt-YesNo "Enable Linux desktop (requires GTK dev libs)?") { flutter config --enable-linux-desktop }
    }
}

Install-Flutter
flutter --version
Setup-Android
Setup-AVD
Enable-Android
Enable-Web
Enable-Desktop
Write-Host "`nRunning flutter doctor..."
flutter doctor -v
Ensure-Frontend-Platforms
Write-EnvScript
